version: '2'
services:
  web:
    container_name: anclaev-com
    image: anclaev-com:latest
    restart: always
    environment:
      - VIRTUAL_HOST=anclaev.com
      - LETSENCRYPT_HOST=anclaev.com
      - VIRTUAL_PORT=80

    networks:
      - "net"

networks:
  net:
    external: true
